# Generated by Django 4.1.2 on 2022-10-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cant_estudiantes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('dependecia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexoP', to='escuela.maestra')),
                ('tipo_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacionP', to='escuela.maestra')),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.grupo')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sexo', to='escuela.maestra')),
                ('tipo_identificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacion', to='escuela.maestra')),
            ],
        ),
        migrations.CreateModel(
            name='asignaturaxgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.TextField()),
                ('nota', models.FloatField()),
                ('logro', models.TextField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.grupo')),
                ('profesor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuela.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.profesor'),
        ),
    ]
